### PR TITLE
Fixed the buffersize

### PR DESCRIPTION
**Pull request by thilohille**
According specs the buffer for the chunks hashed into leaf_node_digests should be 64000.
Should fix issue#4.

### CODE REVIEW

**Comment by Alexander-N** [comment]
Thanks, I don't know where that ` 20 * 1024 * 1024` was coming from :-). Maybe you could also add a test case for #4?

**Comment by thilohille** [comment]
Done and tests pass. I think you can close #4. Rust is kindof new to me therefore i could not see immdeately if this wasnt connected to the odd-even handling :-)

**Comment by Alexander-N** [comment]
Thanks! Issues can be closed with [keywords](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords) like this:
closes #4

Also small nit for next time, I would prefer present tense in commit messages for consistency.

**Comment by Alexander-N** [comment]
@thilohille do you need a new release?

**Comment by thilohille** [comment]
Not shure. I think so because instance-id is working for files > 64k now. But it seems a bit overkill for a oneliner.

**Comment by Alexander-N** [comment]
Ok, you can just ping me if you need one.

**Pull request merged**
